public enum TipoAccion
{
  TiroLibreIntentado,
  TiroLibreConvertido,
  DosPuntosIntentado,
  DosPuntosConvertido,
  TresPuntosIntentado,
  TresPuntosConvertido,
  ReboteOfensivo,
  ReboteDefensivo,
  Bloqueo,
  Asistencia,
  Perdida,
  Recupero,
  FaltaPersonal,
  FaltaAntideportiva,
  FaltaCometida,
  PasaATitular,
  PasaASuplente,
  TiempoMuerto,  
  FaltaTecnica
}